apiVersion: v1
kind: Service
metadata:
  name: influxdb-service 
spec:
  selector:
    app: influxdb
  ports:
  - name: gui
    port: 7001 #cluster internal address
    targetPort: 8086
    #nodePort: 30037 #cluster externel address