apiVersion: batch/v1
kind: Job
metadata:
  name: influxdb-setup
  namespace: monitoring
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: create-credentials
          image: quay.io/influxdb/influxdb:v2.0.3
          command:
            - influx
          args:
            - setup
            - --bucket
            - measurements
            - --org
            - digitaltwin
            - --password
            - testpw
            - --username
            - pascal
            - --token
            - secret-token
            - --force