apiVersion: v1
kind: Service
metadata:
  name: graphdb-service 
spec:
  selector:
    app: graphdb
  ports:
  - name: gui-api
    port: 7001 #cluster internal address
    targetPort: 7200
    #nodePort: 30047 #cluster externel address